### PR TITLE
avoid recommending naming environments "null"

### PR DESCRIPTION
**Pull request by bast**
I suggest this because:

- I use `--prefix` myself "always", using a name and did not know this can
  be problematic. I don't see the problem but perhaps there is a problem
  that I don't see.

- @annefou gave a good comment that a "null" name can be a problem for
  somebody who takes my `environment.yml` and wants to install it into
  the default folder, without `--prefix`.

- When looking at my `environment.yml`, I like if the name is
  descriptive.

For this I have removed mentions of "null", except in episode 5 which we
do not cover in our this-week's course.

### CODE REVIEW

**Comment by davidrpugh** [comment]
@bast I think I started using `null` for a name because it some previous version of Conda you needed to do this in order for the `--prefix` command to work. Clearly that is no longer the case. I agree that it is generally a good idea to encourage the use of descriptive names whenever possible. Please resolve the merge conflicts and I will merge this PR.

**Review by davidrpugh — APPROVED** [review]

**Comment by bast** [comment]
Thank you for the explanation! I will resolve the conflict(s) in a moment ...

**Comment by bast** [comment]
OK some other conflict ... working on it.

**Comment by bast** [comment]
"Everything" conflicts now. Because a file got renamed in the meantime (#50) and the new file seems to contain windows line endings. Is this right?

**Comment by bast** [comment]
OK I will try something else. Working on it ...

**Comment by bast** [comment]
OK good. But please scroll again through my change before merging since files shifted and I had to change things on my side.

**Pull request merged**
