### PR TITLE
channels in yml

### PR DESCRIPTION
**Pull request by samumantha**
added:
how to add channels in yml
plus lazy typer hint to conda commad reference for shortening eg --channels to -c

Please check and adjust if needed :)

### CODE REVIEW

**Comment by samumantha** [comment]
ah sorry, I messed up my branches (again!). I think this PR also includes now the changes from the previous PR. Hopefully it does not mess things up. Sorry for confusion from commits and messages here.

**Review by davidrpugh — APPROVED** [review]

**Review by davidrpugh — APPROVED** [review]

**Review by davidrpugh — APPROVED** [review]

**Comment by davidrpugh** [comment]
@samumantha Thanks for the PR! These changes all look good to me. Don't worry about git mistakes. I make the same errors all the time.

**Comment by davidrpugh** [comment]
@samumantha Are you done making changes to this branch or is there more to do? Let me know when it is ready to merge.

**Comment by samumantha** [comment]
this is done

**Comment by samumantha** [comment]
Please merge :) I'll do a few fixes still but rather in new PR

**Pull request merged**
